# Example script. Include in the project's .github/workflows folder.
name: auto-patch-sdk

on:
  schedule:
    - cron: '00 21 * * TUE'
  workflow_dispatch:

jobs:
  update-sdk:
    uses: UKHO/repo-auto-patch/.github/workflows/update-dotnet-sdk.yml@v2
    with:
      include-nuget-packages: "System,Auto"
