name: dependabot-work-item

on:
  pull_request:
    branches:
      - main

jobs:
  create-work-item:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: UKHO/repo-auto-patch/.github/workflows/create-pr-work-item.yml@v2
    with:
      pr-url: ${{ github.event.pull_request.html_url }}
      work-item-title: "HB Dependabot PBI Create Test"
      work-item-description: "Review this PR."
      work-item-tags: "Maritime Safety Information; TD2; Technical Debt"
    secrets:
      ado-pat: ${{ secrets.ADO_TOKEN }}
