# Example script. Include in the project's .github/workflows folder.
name: auto-patch-libman

on:
  schedule:
    - cron: '00 10 * * FRI'
  workflow_dispatch:

jobs:
  update-libman:
    uses: UKHO/repo-auto-patch/.github/workflows/update-libman.yml@v2
    with:
      project-folder: "/DotNetUpdate/WebProject"
      libraries: "jquery,Chart.js,epub.js"
