# Example script. Include in the project's .github/workflows folder.
name: auto-patch-libman

on:
  schedule:
    - cron: '00 10 * * FRI'
  workflow_dispatch:

jobs:
  update-libman:
    uses: UKHO/repo-auto-patch/.github/workflows/update-libman.yml@v1
    with:
      project-folder: "/DotNetUpdate/WebProject"
      libraries: "jquery,Chart.js,epub.js"
      work-item-title: "HB LibMan PBI Create Test"
      work-item-description: "Review this PR."
      work-item-tags: "Maritime Safety Information; TD2; Technical Debt"
    secrets:
      ado-pat: ${{ secrets.ADO_TOKEN }}
